tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
brew "xz"
brew "openssl@3"
brew "readline"
brew "librsvg"
brew "libyaml"
brew "ansible"
brew "automake"
brew "bash-completion"
brew "bison"
brew "chruby"
brew "ctop"
brew "direnv"
brew "eza"
brew "ffmpeg"
brew "gdbm"
brew "gedit"
brew "git"
brew "hashcat"
brew "htop"
brew "libffi"
brew "mas"
brew "ruby-install"
brew "starship"
brew "telnet"
brew "tree"
brew "xpipe"
brew "yadm"
brew "zsh-completions"
brew "hashicorp/tap/terraform"
cask "alt-tab"
cask "cyberduck"
cask "docker"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"
cask "iina"
cask "iterm2"
cask "macfuse"
cask "macs-fan-control"
cask "malwarebytes"
cask "mos"
cask "notion"
cask "obsidian"
cask "postman"
cask "rectangle"
cask "remote-desktop-manager"
cask "teamviewer"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "warp"
cask "wireshark"
mas "AdBlock Pro", id: 1018301773
mas "Bitwarden", id: 1352778147
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pluralsight", id: 431748264
mas "The Unarchiver", id: 425424353
mas "Wappalyzer - Technology profiler", id: 1520333300
mas "‎WhatsApp", id: 310633997
vscode "hashicorp.terraform"
vscode "mhutchie.git-graph"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "redhat.ansible"
vscode "redhat.vscode-yaml"
